---
title: "feature engineering"
author: "Vivek Jason"
date: "10/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#load packages
```{r cars}
rm(list=ls())
library(tidyverse)
library(EpiEstim)
library(readr)
library(zoo)
library (readxl)
```

# National cluster data
```{r pressure, echo=FALSE}
#call the data
national <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/cases_malaysia.csv")

#extract cluster data
cluster <- national %>% select("date", "cases_new", "cases_import", 
                               "cluster_import", "cluster_religious", "cluster_community", "cluster_highRisk", 
                               "cluster_education", "cluster_detentionCentre", "cluster_workplace")

#write to the data
write.csv(cluster, "P:/COVID-19/c19-epi4msia-data/data/dynamic/cluster.csv")
```

# National case and death data
```{r pressure, echo=FALSE}
#call the data
cases_mas <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/cases_malaysia.csv")
deaths_mas <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/deaths_malaysia.csv")
cases_state <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/cases_state.csv")
deaths_state <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/deaths_state.csv")

#extract natioal data
cases_mas <- cases_mas %>% mutate(cases_truncate=cases_new-cases_import-cluster_detentionCentre,
                                  state="Malaysia",
                                  ma_7day_cases=rollmean(cases_new, k = 7, fill = "extend"),
                                  ma_7day_cases_truncate=rollmean(cases_truncate, k = 7, fill = "extend"),
                                  ma_7day_cases_truncate=ifelse(is.na(ma_7day_cases_truncate),ma_7day_cases, ma_7day_cases_truncate),
                                  rollcases_7d=rollsum(cases_new, k=7,fill=NA, align="right"),
                                  time=seq(1, nrow(cases_mas),1)) %>%
  select("date","time", "state", "cases_new", "cases_import", "cases_recovered", "cases_active", "cases_cluster", "cases_pvax", "cases_fvax", "cases_child", 
         "cases_adolescent", "cases_adult", "cases_elderly", "cases_truncate", "ma_7day_cases", "ma_7day_cases_truncate", "rollcases_7d")

#extract state case data
cases_state <- cases_state %>% mutate(cases_truncate=cases_new-cases_import) %>%
  group_by(state) %>%mutate(ma_7day_cases=rollmean(cases_new, k = 7, fill = "extend"),
                            ma_7day_cases_truncate=rollmean(cases_truncate, k = 7, fill = "extend"),
                            ma_7day_cases_truncate=ifelse(is.na(ma_7day_cases_truncate),ma_7day_cases, ma_7day_cases_truncate),
                            rollcases_7d=rollsum(cases_new, k=7,fill=NA, align="right"),
                            time=seq(1, nrow(cases_mas),1)) %>%
  select("date", "time", "state", "cases_new", "cases_import", "cases_recovered", "cases_active", "cases_cluster", "cases_pvax", "cases_fvax", "cases_child", 
         "cases_adolescent", "cases_adult", "cases_elderly", "cases_truncate", "ma_7day_cases", "ma_7day_cases_truncate", "rollcases_7d")
  
#extract national deaths
deaths_mas <-  deaths_mas %>% mutate(state="Malaysia",
                                  ma_7day_deaths=rollmean(deaths_new, k = 7, fill = "extend"),
                                  rolldeaths_7d=rollsum(deaths_new, k=7,fill=NA, align="right"))

#extract state deaths
deaths_state <-  deaths_state %>% group_by(state) %>%
  mutate(ma_7day_deaths=rollmean(deaths_new, k = 7, fill = "extend"),
         rolldeaths_7d=rollsum(deaths_new, k=7,fill=NA, align="right"))

#merge sets
cases <- bind_rows (cases_mas, cases_state)
deaths <- bind_rows(deaths_mas, deaths_state)
transmission <- left_join(cases, deaths, by=c("date", "state")) 

#divide into rt set and estimate
rt_input <- transmission %>% select (date, state, ma_7day_cases_truncate) %>%
  pivot_wider(id_cols=date,
              names_from=state, 
              values_from=ma_7day_cases_truncate) %>%
 replace(is.na(.), 0)

#create a dummy table
rt_output <- data.frame(time=seq(8,nrow(rt_input),1),
                   "Malaysia" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Johor" = rep(NA, nrow(rt_input)-7),
                   "Kedah" = rep(NA, nrow(rt_input)-7),
                   "Kelantan" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Melaka" = rep(NA, nrow(rt_input)-7),
                   "Negeri Sembilan" = rep(NA, nrow(rt_input)-7),
                   "Pahang" = rep(NA, nrow(rt_input)-7),
                   "Perak" = rep(NA, nrow(rt_input)-7),
                   "Perlis" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Pulau Pinang" = rep(NA, nrow(rt_input)-7),
                   "Sabah" = rep(NA, nrow(rt_input)-7),
                   "Sarawak" = rep(NA, nrow(rt_input)-7),
                   "Selangor" = rep(NA, nrow(rt_input)-7),
                   "Terengganu" = rep(NA, nrow(rt_input)-7),
                   "W.P. Kuala Lumpur" = rep(NA, nrow(rt_input)-7),
                   "W.P. Labuan" = rep(NA, nrow(rt_input)-7),
                   "W.P. Putrajaya" = rep(NA, nrow(rt_input)-7))

lower_output <- data.frame(time=seq(8,nrow(rt_input),1),
                   "Malaysia" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Johor" = rep(NA, nrow(rt_input)-7),
                   "Kedah" = rep(NA, nrow(rt_input)-7),
                   "Kelantan" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Melaka" = rep(NA, nrow(rt_input)-7),
                   "Negeri Sembilan" = rep(NA, nrow(rt_input)-7),
                   "Pahang" = rep(NA, nrow(rt_input)-7),
                   "Perak" = rep(NA, nrow(rt_input)-7),
                   "Perlis" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Pulau Pinang" = rep(NA, nrow(rt_input)-7),
                   "Sabah" = rep(NA, nrow(rt_input)-7),
                   "Sarawak" = rep(NA, nrow(rt_input)-7),
                   "Selangor" = rep(NA, nrow(rt_input)-7),
                   "Terengganu" = rep(NA, nrow(rt_input)-7),
                   "W.P. Kuala Lumpur" = rep(NA, nrow(rt_input)-7),
                   "W.P. Labuan" = rep(NA, nrow(rt_input)-7),
                   "W.P. Putrajaya" = rep(NA, nrow(rt_input)-7))

upper_output <- data.frame(time=seq(8,nrow(rt_input),1),
                   "Malaysia" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Johor" = rep(NA, nrow(rt_input)-7),
                   "Kedah" = rep(NA, nrow(rt_input)-7),
                   "Kelantan" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Melaka" = rep(NA, nrow(rt_input)-7),
                   "Negeri Sembilan" = rep(NA, nrow(rt_input)-7),
                   "Pahang" = rep(NA, nrow(rt_input)-7),
                   "Perak" = rep(NA, nrow(rt_input)-7),
                   "Perlis" = rep(NA, nrow(rt_input)-7),    # Create example data
                   "Pulau Pinang" = rep(NA, nrow(rt_input)-7),
                   "Sabah" = rep(NA, nrow(rt_input)-7),
                   "Sarawak" = rep(NA, nrow(rt_input)-7),
                   "Selangor" = rep(NA, nrow(rt_input)-7),
                   "Terengganu" = rep(NA, nrow(rt_input)-7),
                   "W.P. Kuala Lumpur" = rep(NA, nrow(rt_input)-7),
                   "W.P. Labuan" = rep(NA, nrow(rt_input)-7),
                   "W.P. Putrajaya" = rep(NA, nrow(rt_input)-7))

#loop the case counts for each state
count <- 2
for(i in 2:ncol(rt_input)) {# for-loop over columns
  rt <- estimate_R(rt_input[,i],
                   method="parametric_si",
                   config = make_config(list(
                     mean_si = 5.12, 
                     std_si = 1.86)))
  rt <- as.data.frame(rt$R[,c(3,5,11)])
  rt_output[,count] <- rt[,1]
  lower_output[,count] <- rt[,1]
  upper_output[,count] <- rt[,1]
  count <- count+1
  }

#pivot rt
rt_output <- rt_output %>% pivot_longer(-time,
                                        names_to = "state",
                                        values_to = "rt")
lower_output <- lower_output %>% pivot_longer(-time,
                                        names_to = "state",
                                        values_to = "lower")
upper_output <- upper_output %>% pivot_longer(-time,
                                        names_to = "state",
                                        values_to = "upper")

#join up the rt to the transmission set
transmission <- transmission %>% left_join(rt_output, by=c("time", "state")) %>%
  left_join(lower_output, by=c("time", "state")) %>%
  left_join(upper_output, by=c("time", "state"))

#input population data
pop <- read_excel("P:/COVID-19/R0 Malaysia/data/population_healthcapacity/state_data_demographics_only_v2.xlsx", 
    col_types = c("text", "numeric", "text", 
        "text", "text", "text", "text", "text", 
        "text", "text", "text", "text", "text", 
        "text"))
pop <- pop %>% select (state, population_new)

#calaculate moving ir and mr
transmission <-  transmission %>% left_join(pop, by="state") %>%
  group_by(state) %>%
  mutate(ir_7day=(rollcases_7d/population_new)*100000,
         mr_7day=(rolldeaths_7d/population_new)*100000) 

#write to the data
write.csv(transmission, "P:/COVID-19/c19-epi4msia-data/data/dynamic/transmission.csv")
```

#hospital capacity
```{r}
#load data
hospital <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/hospital.csv")
icu <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/icu.csv")
pkrc <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/pkrc.csv")

#extract an occupancy rate for each level - state and national
bor_national <- hospital %>% dplyr::select(date, beds, hosp_covid, hosp_pui, hosp_noncovid) %>%
  group_by(date) %>%
  summarise(hosp_beds=sum(beds),
         hosp_covid=sum(hosp_covid),
         hosp_pui=sum(hosp_pui),
         hosp_noncovid=sum(hosp_noncovid),
         hosp=sum(hosp_covid+hosp_pui+hosp_noncovid),
         ) %>%
  mutate(bor=(hosp/hosp_beds)*100,
         state="Malaysia") %>%
  dplyr::select(date, state, bor, hosp_covid, hosp_pui, hosp_noncovid, hosp_beds) 

bor_state <- hospital %>% dplyr::select(date, state, beds, hosp_covid, hosp_pui, hosp_noncovid) %>%
  mutate(bor=((hosp_covid+hosp_pui+hosp_noncovid)/beds)*100) %>%
  dplyr::select(date, state, bor, hosp_covid, hosp_pui, hosp_noncovid, beds) %>%
  rename(date=date, state=state, bor=bor, hosp_covid=hosp_covid, 
         hosp_pui=hosp_pui, hosp_noncovid=hosp_noncovid, hosp_beds=beds)

icu_national <- icu %>% dplyr::select(date, beds_icu_total, icu_covid, icu_noncovid, icu_pui) %>%
  group_by(date) %>%
  summarise(icu_beds=sum(beds_icu_total),
            icu_covid=sum(icu_covid),
            icu_pui=sum(icu_pui),
            icu_noncovid=sum(icu_noncovid),
            icu=sum(icu_covid+icu_pui+icu_noncovid))%>%
  mutate(ior=(icu/icu_beds)*100,
         state="Malaysia") %>%
  dplyr::select(date, state, ior, icu_pui, icu_covid, icu_noncovid, icu_beds)

icu_state <- icu %>% dplyr::select(date, state, beds_icu_total, icu_covid, icu_noncovid, icu_pui) %>%
  mutate(ior=((icu_pui+icu_covid+icu_noncovid)/beds_icu_total)*100) %>%
  dplyr::select(date, state, ior, icu_pui, icu_covid, icu_noncovid, beds_icu_total)

vent_national <- icu %>% dplyr::select(date, vent, vent_port, vent_pui, vent_covid, vent_noncovid) %>%
  group_by(date) %>%
  summarise(vent_beds=sum(vent+vent_port),
            vent_covid=sum(vent_covid),
            vent_pui=sum(vent_pui),
            vent_noncovid=sum(vent_noncovid),
            ven=sum(vent_covid+vent_pui+vent_noncovid))%>%
  mutate(vor=(ven/vent_beds)*100,
         state="Malaysia") %>%
  dplyr::select(date, state, vor, vent_covid, vent_pui, vent_noncovid, vent_beds)

vent_state <- icu %>% dplyr::select(date, state, vent, vent_port, vent_pui, vent_covid,vent_noncovid) %>%
  mutate(vor=((vent_covid+vent_pui+vent_noncovid)/(vent+vent_port))*100) %>%
  dplyr::select(date, state, vor, vent_covid, vent_pui, vent_noncovid, vent, vent_port)

pkrc_national <- pkrc %>% dplyr::select(date, pkrc_covid, pkrc_pui, pkrc_noncovid, beds) %>%
  group_by(date) %>%
  summarise(pkrc=sum(pkrc_covid+pkrc_pui+pkrc_noncovid),
            pkrc_covid=sum(pkrc_covid),
            pkrc_pui=sum(pkrc_pui),
            pkrc_noncovid=sum(pkrc_noncovid),
            pkrc_beds=sum(beds))%>%
  mutate(por=(pkrc/pkrc_beds)*100, 
         state="Malaysia") %>%
  dplyr::select(date, state, por, pkrc_covid, pkrc_pui, pkrc_noncovid, pkrc_beds) 

pkrc_state <- pkrc %>% dplyr::select(date, state, pkrc_covid, pkrc_pui, pkrc_noncovid, beds) %>%
  mutate(por=((pkrc_covid+pkrc_pui+pkrc_noncovid)/beds)*100) %>%
  dplyr::select(date, state, por, pkrc_covid, pkrc_pui, pkrc_noncovid, beds) %>%
  rename(date=date, state=state, por=por, pkrc_covid=pkrc_covid, pkrc_pui=pkrc_pui, 
         pkrc_noncovid=pkrc_noncovid, pkrc_beds=beds)

#merge the state and national rates
hosp_national <- bor_national %>% 
  left_join(icu_national, by=c("date", "state")) %>%
  left_join(vent_national, by=c("date", "state")) %>%
  left_join(pkrc_national, by=c("date", "state")) %>%
  mutate(date=as.Date(date))

hosp_state <- bor_state %>% 
  left_join(icu_state, by=c("date", "state")) %>%
  left_join(vent_state, by=c("date", "state")) %>%
  left_join(pkrc_state, by=c("date", "state"))  %>%
  mutate(date=as.Date(date)) 

#merge together
capacity <- bind_rows(hosp_national, hosp_state)

#write to the data
write.csv(capacity, "P:/COVID-19/c19-epi4msia-data/data/dynamic/capacity.csv")
```

#testing
```{r}
#load data
#testinf data
test_mas <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/tests_malaysia.csv")
test_state <- read.csv("https://raw.githubusercontent.com/MoH-Malaysia/covid19-public/main/epidemic/tests_state.csv")

#edit data
test_mas <- test_mas %>% 
  mutate(tests_new=rtk.ag+pcr,
         state="Malaysia",
         date=as.Date(date)) %>%
  select(date, state, tests_new, rtk.ag, pcr)

test_state <- test_state %>% 
  mutate(tests_new=rtk.ag+pcr,
         date=as.Date(date)) %>% 
  select(date, state, tests_new, rtk.ag, pcr) 

#merge
test <- bind_rows(test_mas, test_state)

#add population data
pop <- read.csv("https://raw.githubusercontent.com/CITF-Malaysia/citf-public/main/static/population.csv")
pop <- pop %>% select(state, pop)
test <- left_join(test, pop, by="state")

#load case data- pull from above
test_cases <- transmission %>% select(date, state, cases_new) %>%
  mutate(date=as.Date(date))

#merge with test state
test <-  left_join(test, test_cases, by=c("date", "state"))

#add the new_cases, positivity rate and testing rate
test <- test %>% dplyr::group_by(state) %>%
  mutate(positivity_rate= round((cases_new/tests_new)*100, 2),
         testing_rate=round((tests_new/pop)*1000),2) %>% 
  dplyr::select(date, state, rtk.ag, pcr, tests_new, positivity_rate, testing_rate) 

#write to dataset
write.csv(test, "P:/COVID-19/c19-epi4msia-data/data/dynamic/testing.csv")
```

#vaccinations
```{r}
#load data
pop <- read.csv("https://raw.githubusercontent.com/CITF-Malaysia/citf-public/main/static/population.csv")
vax_state <- read.csv("https://raw.githubusercontent.com/CITF-Malaysia/citf-public/main/vaccination/vax_state.csv")
vax_malaysia <- read.csv("https://raw.githubusercontent.com/CITF-Malaysia/citf-public/main/vaccination/vax_malaysia.csv")
vaxreg_malaysia <- read.csv("https://raw.githubusercontent.com/CITF-Malaysia/citf-public/main/registration/vaxreg_malaysia.csv")
vaxreg_state <- read.csv("https://raw.githubusercontent.com/CITF-Malaysia/citf-public/main/registration/vaxreg_state.csv")

#add classifying variable
vaxreg_malaysia$state <- "Malaysia"
vax_malaysia$state <- "Malaysia"

#bind the state and national sets
vax <- bind_rows(vax_malaysia, vax_state)
vaxreg <- bind_rows(vaxreg_malaysia, vaxreg_state)
vax<- full_join(vax, vaxreg, by=c("date","state")) %>%
  full_join(pop, by="state") %>%
  mutate(state=ifelse(state=="Selangor", "Klang valley",
                      ifelse(state=="W.P. Putrajaya","Klang valley",
                             ifelse(state=="W.P. Kuala Lumpur", "Klang valley", state)))) %>%
  dplyr::select(date, state, cumul_partial, cumul_full, total,pop) %>%
  group_by(state, date) %>% 
  summarise(cumul_partial=sum(cumul_partial),
            cumul_full=sum(cumul_full),
            total=sum(total),
            pop=sum(pop)) %>%
  mutate(perc_vax1=(cumul_partial/pop),
         perc_vax2=(cumul_full/pop),
         perc_reg=(total/pop),
         perc_pop=1,
         diff_vax2= perc_vax2,
         diff_vax1=perc_vax1-perc_vax2,
         diff_reg=perc_reg-perc_vax1,
         diff_pop=perc_pop-perc_reg)

#write to the database
write.csv(vax, "P:/COVID-19/c19-epi4msia-data/data/dynamic/vaccination.csv")
```

#mobility
```{r}
#load data
Global_Mobility_Report_3_ <- read_csv("https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv")
# FIXME: update this daily 

#add an avergae mobility to the ts_mas dataset
mobility_mas <- Global_Mobility_Report_3_%>% filter(country_region=="Malaysia" & is.na(sub_region_1)) %>%
  select("date", "country_region", "grocery_and_pharmacy_percent_change_from_baseline", "parks_percent_change_from_baseline",
         "retail_and_recreation_percent_change_from_baseline",
         "transit_stations_percent_change_from_baseline", "workplaces_percent_change_from_baseline", 
         "residential_percent_change_from_baseline") %>%
  mutate(date=as.Date(date),
         average=(parks_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline +
                      retail_and_recreation_percent_change_from_baseline)/3) %>%
  rename(date=date, state=country_region,
         recreation=retail_and_recreation_percent_change_from_baseline,
         grocery=grocery_and_pharmacy_percent_change_from_baseline,
         parks=parks_percent_change_from_baseline,
         transit=transit_stations_percent_change_from_baseline,
         work=workplaces_percent_change_from_baseline,
         residence=residential_percent_change_from_baseline)

#clean up state
mobility_state <- Global_Mobility_Report_3_
mobility_state$sub_region_1[is.na(mobility_state$sub_region_1)] <- "country_level"
mobility_state <- mobility_state %>% filter(country_region=="Malaysia", sub_region_1!="country_level") %>%
  select("date", "sub_region_1", "grocery_and_pharmacy_percent_change_from_baseline", "parks_percent_change_from_baseline",
         "retail_and_recreation_percent_change_from_baseline",
         "transit_stations_percent_change_from_baseline", "workplaces_percent_change_from_baseline", 
         "residential_percent_change_from_baseline") %>%
  mutate(date=as.Date(date),
         average=(parks_percent_change_from_baseline + grocery_and_pharmacy_percent_change_from_baseline +
                      retail_and_recreation_percent_change_from_baseline)/3) %>%
  rename(date=date, state=sub_region_1,
         recreation=retail_and_recreation_percent_change_from_baseline,
         grocery=grocery_and_pharmacy_percent_change_from_baseline,
         parks=parks_percent_change_from_baseline,
         transit=transit_stations_percent_change_from_baseline,
         work=workplaces_percent_change_from_baseline,
         residence=residential_percent_change_from_baseline) %>%
  as.data.frame()

#statndardise the states
mobility_state$state[mobility_state$state=="Penang"] <- 'Pulau Pinang'
mobility_state$state[mobility_state$state=="Malacca"] <- 'Melaka'
mobility_state$state[mobility_state$state=="Terengganu"] <- "Terengganu"
mobility_state$state[mobility_state$state=="Labuan Federal Territory"] <- 'W.P. Labuan'
mobility_state$state[mobility_state$state=="Federal Territory of Kuala Lumpur"] <- "W.P. Kuala Lumpur"
mobility_state$state[mobility_state$state=="Putrajaya"] <- 'W.P. Putrajaya'

#convert mobility into a dataframe
mobility <- bind_rows(mobility_mas, mobility_state)

#index the mobility report
write.csv(mobility,  "P:/COVID-19/c19-epi4msia-data/data/dynamic/mobility.csv")
```

voc data
```{r}
#get cumulative cases data
cases <- transmission %>% select(date, state, cases_new) %>%
  group_by(state) %>%
  mutate(cases_sum=cumsum(cases_new),
         date=as.Date(date)) %>%
  select(date, state, cases_sum)

#load voc data
voc_v4 <- read_excel("P:/COVID-19/R0 Malaysia/data/voc/voc_v4.xlsx", 
    sheet = "states", col_types = c("date", 
        "text", "numeric", "text", "text", 
        "text", "text", "text", "text"))

#combine voc and cases data
voc <- voc_v4 %>% dplyr::select(date, state, cases, variant, status) %>%
  mutate(date=as.Date(date)) %>%
  rename(date=date, state=state, variant_count=cases, variant=variant, status=status) 


#calaculate the ratio
voc_ratio <- voc_v4 %>% dplyr::select(date, state, cases) %>%
  mutate(date=as.Date(date)) %>%
  group_by(date, state) %>%
  summarise(n=sum(cases)) %>%
  rename(date=date, state=state, variant_count=n) %>%
  ungroup() %>%
  left_join(cases, by=c("date", "state")) %>%
  group_by(state) %>%
  mutate(cases=cases_sum-lag(cases_sum),
         variant=variant_count-lag(variant_count),
    ratio=(variant/cases)*100) %>%
  select(date, state, ratio)

#write to data tests and cases
write.csv(voc, "P:/COVID-19/c19-epi4msia-data/data/dynamic/voc.csv")
write.csv(voc_ratio, "P:/COVID-19/c19-epi4msia-data/data/dynamic/voc_ratio.csv")
```
