---
title: "COVID-19 Epi4Msia Data"
author: "Vivek Jason"
date: "5/6/2021"
output: html_document
---


```{r setup, include=FALSE}
library(flexdashboard)
library(EpiEstim)
library(R0)
library(tidyverse)
library(readxl)
library(readr)
library(lubridate)
library(httr)
library(zoo)
library(cowplot)
library(viridis)
library(RColorBrewer)
library(plotly)
library(todor)
library(knitr)
library(heatmaply)
library(RcppRoll)
library(gplots)
```


```{r,include=FALSE}
#wrangle the data
###########################################################################################################################################  
############################################data manipulation##############################################################################  
###########################################################################################################################################  
#clear the global environment first and clear the cache
#unlink('index_cache', recursive = TRUE)
#rm(list=ls())
#pull data set of clusters
clusters <- read_csv("P:/COVID-19/R0 Malaysia/data/cluster data/clusters_dashboard.csv", 
    col_types = cols(no = col_number(), bangau = col_number(), 
        benteng = col_number(), benteng_pk = col_number(), 
        date = col_date(format = "%d/%m/%Y"), 
        dti = col_number(), import = col_number(), 
        kepayan = col_number(), laut = col_number(), 
        meru = col_number(), penjara_jawi = col_number(), 
        penjara_reman = col_number(), penjara_sandakan = col_number(), 
        penjara_tapah = col_number(), pts_tawau = col_number(), 
        pulau = col_number(), rumah_merah = col_number(), 
        sivagangga = col_number(), sungai = col_number(), 
        tabligh = col_number(), tawar = col_number(), 
        tembok = col_number(), gk_tawau=col_number(), matambai=col_number(), 
        jalan_harapan=col_number(), bakti=col_number(), tembok_gajah=col_number(), 
        kolam_air=col_number(), hala_mutiara=col_number(), pompod=col_number(),
        pagar_siput=col_number(), pagar_bentong=col_number(), tembok_mempaga=col_number(),
        telok_mas=col_number(), tropika=col_number(), tembok_kemus=col_number(), 
        tembok_nenas=col_number(), teratai=col_number(),sungai_jelok=col_number(),
        tembok_renggam=col_number(), tembok_sgudang=col_number(), tembok_taiping=col_number(),
        bukit_besi=col_number(), pengkalan_chepa=col_number(), tembok_bendera=col_number(),
        jln_awang=col_number(), dti_persiaran_wawasan=col_number(), dti_machap_umboo=col_number(),
        tembok_muhasabah=col_number(), imigresen_semuja=col_number(), dti_juru=col_number(),
        dti_jln_duta=col_number(), bukit_chagar=col_number(), sri_aman=col_number(), 
        padang_hijau=col_number(), choh2=col_number(), jln_salleh=col_number(),
        dti_lenggeng=col_number(), dti_sandakan=col_number(), pagar_siput2=col_number(),
        sri_lalang=col_number(), kg_selamat=col_number(), pagar_rimba=col_number(),
        meru_utama=col_number()))


#pull new data set
df <- read_csv("P:/COVID-19/R0 Malaysia/data/incidence/covid-19_my.csv", 
      col_types = cols(date = col_date(format = "%d/%m/%Y"), 
        new_cases = col_number(), new_deaths = col_number(), 
        total_cases = col_number(), total_deaths = col_number(), 
        recover = col_number(), total_recover = col_number(), 
        icu = col_number(), support = col_number()))

#lock down one set#NO MANIPULATION#
core_set <- df

#cut out the dates to join with cluster
new <- df[21:as.numeric(Sys.Date()-18261),c(1,3,4,7)] # TODO: if elapsed by a day +1 to the constant (contstant=18260) (+1 for each elapsed day)
new$no <- seq(1:as.numeric(Sys.Date()-18281)) # TODO: if elapsed by a day +1 to the constant (contstant=18280)  (+1 for each elapsed day)
new$date <- as.Date(new$date)

#merge the two sets
df <- full_join(new, clusters, by=c("no","date"))

#create a special variable for all immigration and prison outbreaks
df$ins <- df$dti+df$tembok+df$benteng_pk+df$penjara_reman+df$penjara_jawi+df$kepayan+df$penjara_tapah+
  df$rumah_merah+df$pts_tawau+df$penjara_sandakan+df$gk_tawau+df$matambai+df$jalan_harapan+df$bakti+df$sibuga+
  df$tembok_gajah + df$kolam_air + df$hala_mutiara + df$pompod + df$pagar_siput + df$pagar_bentong + 
  df$tembok_mempaga + df$telok_mas +df$tropika + df$tembok_kemus + df$tembok_nenas +df$sungai_jelok +df$tembok_renggam +
  df$tembok_sgudang +  df$tembok_taiping + df$bukit_besi + df$pengkalan_chepa + df$tembok_bendera +df$jln_awang + 
  df$dti_persiaran_wawasan + df$dti_machap_umboo + df$tembok_muhasabah +df$imigresen_semuja + df$dti_juru + 
  df$ dti_jln_duta + df$bukit_chagar +df$sri_aman + df$padang_hijau + df$choh2 + df$jln_salleh + df$dti_lenggeng +
  df$dti_sandakan + df$pagar_siput2 + df$sri_lalang + df$kg_selamat + df$pagar_rimba + df$meru_utama

##########################################################################################
#arbitrary cut of point for visualisation of clusters with at least 150 cases or more
##########################################################################################
#join the 2 sets
df$daily <- df$new_cases-df$ins-df$import#benteng ld has begun in an institution but quickly spiralled into community as well

###########################################################################################################################################  
############################################estimate the rt using cori et al method#########################################################  
###########################################################################################################################################  
# sub plot a - policy and events across outbreak
#create control parameters for MCMC
res_parametric_si <- estimate_R(df$daily, 
                                method="parametric_si",
                                config = make_config(list(
                                  mean_si = 5.12, #lit review
                                  std_si = 1.86))#lit review
)

#extract values into a dataframe
mas_r0_df <- as.data.frame(res_parametric_si$R)
###########################################################################################################################################  
############################################PLAY AROUND WITH the SI####################################################################### 
###########################################################################################################################################
#THE SI DISTRIBUTION- LINK TO si_intervals.rmd
#including the walinga teunis and riberio estimations
#####REVISIT THIS####
###########NEED TO REALLY THINK OF A WAY TO ESTIMATE THE SI INTERVAL#############
######################################################################################

###########################################################################################################################################  
############################################POSTPROCESSING#################################################################################  
########################################################################################################################################
#create a shell data frame for the first 7 days
shell_df <- data.frame(end=seq(1:7),
                       start=rep(1,7),
                       rt=rep(NA,7),
                       lower=rep(NA,7),
                       upper=rep(NA,7))

mas_r0_df <-  mas_r0_df %>% select ("t_start", "t_end", "Mean(R)", "Quantile.0.025(R)","Quantile.0.975(R)") %>%
  rename(start="t_start", end="t_end", rt="Mean(R)", lower="Quantile.0.025(R)",upper="Quantile.0.975(R)") 
mas_r0_df <- bind_rows(shell_df, mas_r0_df)


#create new data frame
df$date <- as.Date(df$date)
mas_r0_df$date <- as.Date(df$date)

#set the healthcare capacity
##define key paremeters of amalysian population
mas_pop <- 32730000
mas_bed <- 3825+12235 +4394 +1000 + 4002 #last updated on 25 December 2020
mas_icu <- 871
mas_ven <- 1581

#merge the datasets
ts_mas <- left_join(df, mas_r0_df, by="date") %>%
  select(date, new_cases, recover, new_deaths, daily, ins, import, rt, lower, upper) %>%
  rename(date=date, new=new_cases, discharged=recover, death=new_deaths, deaily=daily, 
         ins=ins, import=import, rt=rt, lower=lower, upper=upper) %>%
  mutate(daily_ma = rollmean(new, k = 7, fill = "extend"),
         icu=core_set$icu[21:nrow(core_set)],
         ven=core_set$support[21:nrow(core_set)],
         cumsum=cumsum(new),
         cumsum_death=cumsum(death),
         cumsum_discharged=cumsum(discharged),
         active=cumsum-cumsum_discharged-cumsum_death,
         mas_pop=32730000,
         mas_bed=3825+12235 +4394 +1000 + 4002,
         mas_icu=871, 
         mas_ven=1581,
         incident14=rollsum(new,k=14,fill=NA, align="right"),
         incidence=round((cumsum/mas_pop)*100000,2),
         incidence14_rate=round((incident14/mas_pop)*100000,2),
         bed_perc5=(active/mas_bed)*100, 
         bed_perc5=ifelse(bed_perc5<0, 0, bed_perc5),
         icu_perc=(icu/mas_icu)*100, 
         icu_perc=ifelse(icu_perc<0, 0, icu_perc),
         ven_perc=(ven/mas_ven)*100,
         ven_perc=ifelse(ven_perc<0, 0, ven_perc))

################################################################################################################################
############################################mobility reports######################################################################
################################################################################################################################
#import the mobility data and get them into states
#download link
#https://www.gstatic.com/covid19/mobility/Global_Mobility_Report.csv

#load data
Global_Mobility_Report_3_ <- read_csv("P:/COVID-19/R0 Malaysia/data/mobility/Global_Mobility_Report_210505.csv", 
                                      col_types = cols(census_fips_code = col_character(), 
                                                       date = col_character(), grocery_and_pharmacy_percent_change_from_baseline = col_number(), 
                                                       iso_3166_2_code = col_character(), 
                                                       parks_percent_change_from_baseline = col_number(), 
                                                       residential_percent_change_from_baseline = col_number(), 
                                                       retail_and_recreation_percent_change_from_baseline = col_number(), 
                                                       sub_region_1 = col_character(), sub_region_2 = col_character(), 
                                                       transit_stations_percent_change_from_baseline = col_number(), 
                                                       workplaces_percent_change_from_baseline = col_number()))
# FIXME: update this daily 

#add an avergae mobility to the ts_mas dataset
malaysia_mobility <- Global_Mobility_Report_3_%>% filter(country_region=="Malaysia" & is.na(sub_region_1)) %>%
  select() %>%
  rename("recreation"="retail_and_recreation_percent_change_from_baseline",
         "grocery"="grocery_and_pharmacy_percent_change_from_baseline",
         "parks"="parks_percent_change_from_baseline")
malaysia_mobility <- malaysia_mobility[,c(2,8:14)]
malaysia_mobility$date <- as.Date(malaysia_mobility$date)
ts_mas <- full_join(ts_mas, malaysia_mobility, by="date")
ts_mas$average <- (ts_mas$parks_percent_change_from_baseline + ts_mas$grocery_and_pharmacy_percent_change_from_baseline +
                      ts_mas$retail_and_recreation_percent_change_from_baseline)/3

#chnge the names to shorter ones
names(ts_mas)[names(ts_mas)==]=
names(ts_mas)[names(ts_mas)==]=
names(ts_mas)[names(ts_mas)==]=
names(ts_mas)[names(ts_mas)=="transit_stations_percent_change_from_baseline"]="transit"
names(ts_mas)[names(ts_mas)=="workplaces_percent_change_from_baseline"]="work"
names(ts_mas)[names(ts_mas)=="residential_percent_change_from_baseline"]="residence"

```



```{r, include=FALSE}
#get the data for states in
#load Malaysian data by state from data.world
df <- read_csv("P:/COVID-19/R0 Malaysia/data/incidence/covid-19_my_state_v2.csv", 
        col_types = cols(date = col_date(format = "%d/%m/%Y"), 
        new_cases = col_number(), total_cases = col_number(), 
        new_deaths = col_number(), total_deaths = col_number()))
state <- df

#repeat total cases for first 2 days
state$new_cases[c(1:16)] <- state$total_cases[c(1:16)]

#remove NA's
state[is.na(state)] <- 0
state$date <- as.Date(state$date)

#change selected state spelling
state$state[state$state=="PERLIS"] <- 'Perlis'
state$state[state$state=="KEDAH"] <- 'Kedah'
state$state[state$state=="PULAU PINANG"] <- 'Pulau Pinang'
state$state[state$state=="PERAK"] <- 'Perak'
state$state[state$state=="SELANGOR"] <- 'Selangor'
state$state[state$state=="NEGERI SEMBILAN"] <- 'Negeri Sembilan'
state$state[state$state=="MELAKA"] <- 'Melaka'
state$state[state$state=="JOHOR"] <- 'Johor'
state$state[state$state=="PAHANG"] <- 'Pahang'
state$state[state$state=="TERENGGANU"] <- "Terengganu"
state$state[state$state=="KELANTAN"] <- 'Kelantan'
state$state[state$state=="SABAH"] <- 'Sabah'
state$state[state$state=="SARAWAK"] <- 'Sarawak'
state$state[state$state=="WP LABUAN"] <- 'W.P. Labuan'
state$state[state$state=="WP KUALA LUMPUR"] <- "W.P. Kuala Lumpur"
state$state[state$state=="WP PUTRAJAYA"] <- 'W.P. Putrajaya'

#clean up data
mobility <- Global_Mobility_Report_3_
mobility$sub_region_1[is.na(mobility$sub_region_1)] <- "country_level"
mobility <- mobility %>% filter(country_region=="Malaysia", sub_region_1!="country_level")
mobility$date <- as.Date(mobility$date)
mobility <- mobility[,-c(1,4,5,6,7,8)]
colnames(mobility) <- c("country","state","date","recreation","grocery", "parks","transit","work","residence")

#statndardise the states
mobility$state[mobility$state=="Penang"] <- 'Pulau Pinang'
mobility$state[mobility$state=="Malacca"] <- 'Melaka'
mobility$state[mobility$state=="Terengganu"] <- "Terengganu"
mobility$state[mobility$state=="Labuan Federal Territory"] <- 'W.P. Labuan'
mobility$state[mobility$state=="Federal Territory of Kuala Lumpur"] <- "W.P. Kuala Lumpur"
mobility$state[mobility$state=="Putrajaya"] <- 'W.P. Putrajaya'

#convert mobility into a dataframe
mobility <- as.data.frame(mobility)

#######################################################################################################
#filter: perlis
perlis <- state %>% filter(state=="Perlis")

#create control parameters for MCMC
perlis_r0 <- estimate_R(perlis$new_cases, 
                        method="parametric_si",
                        config = make_config(list(
                          mean_si = 5.12, 
                          std_si = 1.86))#lit review
)

#create df of parameters
plot(perlis_r0)
perlis_r0_df<- as.data.frame(perlis_r0$R[,c(1:3,5,11)])
perlis_r0_df$date <- seq(from=as.Date("2020-03-20"),to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
perlis_r0_df <- perlis_r0_df[,3:6]
perlis_r0_df$state <- "Perlis"
colnames(perlis_r0_df) <- c("rt","lower","upper","date","state")
perlis_r0_df$case <- perlis$new_cases[8:nrow(perlis)]
perlis_r0_df$total_case <- perlis$total_cases[8:nrow(perlis)]
perlis_r0_df$new_death <- perlis$new_deaths[8:nrow(perlis)]

perlis_r0_df$active_cases_part3[4:nrow(perlis_r0_df)] <- diff(perlis_r0_df$total_case, lag=3)
perlis_r0_df$active_cases3 <- perlis_r0_df$active_cases_part3-perlis_r0_df$new_death
perlis_r0_df$active_cases3[1:3] <- cumsum(perlis_r0_df$case[1:3])-perlis_r0_df$new_death[1:3]
perlis_r0_df$active_cases3[perlis_r0_df$active_cases3<=0] <- 0

perlis_r0_df$active_cases_part5[6:nrow(perlis_r0_df)] <- diff(perlis_r0_df$total_case, lag=5)
perlis_r0_df$active_cases5 <- perlis_r0_df$active_cases_part5-perlis_r0_df$new_death
perlis_r0_df$active_cases5[1:5] <- cumsum(perlis_r0_df$case[1:5])-perlis_r0_df$new_death[1:5]
perlis_r0_df$active_cases5[perlis_r0_df$active_cases5<=0] <- 0

perlis_r0_df$active_cases_part9[10:nrow(perlis_r0_df)] <- diff(perlis_r0_df$total_case, lag=9)
perlis_r0_df$active_cases9 <- perlis_r0_df$active_cases_part9-perlis_r0_df$new_death
perlis_r0_df$active_cases9[1:9] <- cumsum(perlis_r0_df$case[1:9])-perlis_r0_df$new_death[1:9]
perlis_r0_df$active_cases9[perlis_r0_df$active_cases9<=0] <- 0

perlis_r0_df <- perlis_r0_df[1:nrow(perlis_r0_df),]
perlis_r0_df

#create moving averages
perlis_r0_df <- perlis_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
perlis_r0_df$incident14 <- rollsum(perlis_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_perlis <- mobility %>% filter (state=="Perlis" & date >as.Date("2020-03-19")) 

#create a new varaible for state
perlis<- full_join(perlis_r0_df, mobility_perlis, by=c("date","state"))

#add ab average
perlis$average <- (perlis$recreation+perlis$grocery+perlis$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: kedah
kedah <- state %>% filter(state=="Kedah")

#create control parameters for MCMC
kedah_r0 <- estimate_R(kedah$new_cases, 
                       method="parametric_si",
                       config = make_config(list(
                         mean_si = 5.12, 
                         std_si = 1.86))#lit review
)

#create df of parameters
plot(kedah_r0)
kedah_r0_df<- as.data.frame(kedah_r0$R[,c(1:3,5,11)])
kedah_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
kedah_r0_df <- kedah_r0_df[,3:6]
kedah_r0_df$state <- "Kedah"
colnames(kedah_r0_df) <- c("rt","lower","upper","date","state")
kedah_r0_df$case <- kedah$new_cases[8:nrow(kedah)]
kedah_r0_df$total_case <- kedah$total_cases[8:nrow(kedah)]
kedah_r0_df$new_death <- kedah$new_deaths[8:nrow(kedah)]

kedah_r0_df$active_cases_part3[4:nrow(kedah_r0_df)] <- diff(kedah_r0_df$total_case, lag=3)
kedah_r0_df$active_cases3 <- kedah_r0_df$active_cases_part3-kedah_r0_df$new_death
kedah_r0_df$active_cases3[1:3] <- cumsum(kedah_r0_df$case[1:3])-kedah_r0_df$new_death[1:3]
kedah_r0_df$active_cases3[kedah_r0_df$active_cases3<=0] <- 0

kedah_r0_df$active_cases_part5[6:nrow(kedah_r0_df)] <- diff(kedah_r0_df$total_case, lag=5)
kedah_r0_df$active_cases5 <- kedah_r0_df$active_cases_part5-kedah_r0_df$new_death
kedah_r0_df$active_cases5[1:5] <- cumsum(kedah_r0_df$case[1:5])-kedah_r0_df$new_death[1:5]
kedah_r0_df$active_cases5[kedah_r0_df$active_cases5<=0] <- 0

kedah_r0_df$active_cases_part9[10:nrow(kedah_r0_df)] <- diff(kedah_r0_df$total_case, lag=9)
kedah_r0_df$active_cases9 <- kedah_r0_df$active_cases_part9-kedah_r0_df$new_death
kedah_r0_df$active_cases9[1:9] <- cumsum(kedah_r0_df$case[1:9])-kedah_r0_df$new_death[1:9]
kedah_r0_df$active_cases9[kedah_r0_df$active_cases9<=0] <- 0

kedah_r0_df <- kedah_r0_df[1:nrow(kedah_r0_df),]
kedah_r0_df

#create moving averages
kedah_r0_df <- kedah_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
kedah_r0_df$incident14 <- rollsum(kedah_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_kedah <- mobility %>% filter (state=="Kedah" & date >as.Date("2020-03-19")) 

#create a new varaible for state
kedah<- full_join(kedah_r0_df, mobility_kedah, by=c("date","state"))

#add ab average
kedah$average <- (kedah$recreation+kedah$grocery+kedah$parks)/3

#################################################################################################################################
#################################################################################################################################
#filter: penang
penang <- state %>% filter(state=="Pulau Pinang")

#create control parameters for MCMC
penang_r0 <- estimate_R(penang$new_cases, 
                        method="parametric_si",
                        config = make_config(list(
                          mean_si = 5.12, 
                          std_si = 1.86))#lit review
)

#create df of parameters
plot(penang_r0)
penang_r0_df<- as.data.frame(penang_r0$R[,c(1:3,5,11)])
penang_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
penang_r0_df <- penang_r0_df[,3:6]
penang_r0_df$state <- "Pulau Pinang"
colnames(penang_r0_df) <- c("rt","lower","upper","date","state")
penang_r0_df$case <- penang$new_cases[8:nrow(penang)]
penang_r0_df$total_case <- penang$total_cases[8:nrow(penang)]
penang_r0_df$new_death <- penang$new_deaths[8:nrow(penang)]

penang_r0_df$active_cases_part3[4:nrow(penang_r0_df)] <- diff(penang_r0_df$total_case, lag=3)
penang_r0_df$active_cases3 <- penang_r0_df$active_cases_part3-penang_r0_df$new_death
penang_r0_df$active_cases3[1:3] <- cumsum(penang_r0_df$case[1:3])-penang_r0_df$new_death[1:3]
penang_r0_df$active_cases3[penang_r0_df$active_cases3<=0] <- 0

penang_r0_df$active_cases_part5[6:nrow(penang_r0_df)] <- diff(penang_r0_df$total_case, lag=5)
penang_r0_df$active_cases5 <- penang_r0_df$active_cases_part5-penang_r0_df$new_death
penang_r0_df$active_cases5[1:5] <- cumsum(penang_r0_df$case[1:5])-penang_r0_df$new_death[1:5]
penang_r0_df$active_cases5[penang_r0_df$active_cases5<=0] <- 0

penang_r0_df$active_cases_part9[10:nrow(penang_r0_df)] <- diff(penang_r0_df$total_case, lag=9)
penang_r0_df$active_cases9 <- penang_r0_df$active_cases_part9-penang_r0_df$new_death
penang_r0_df$active_cases9[1:9] <- cumsum(penang_r0_df$case[1:9])-penang_r0_df$new_death[1:9]
penang_r0_df$active_cases9[penang_r0_df$active_cases9<=0] <- 0

penang_r0_df <- penang_r0_df[1:nrow(penang_r0_df),]
penang_r0_df

#create moving averages
penang_r0_df <- penang_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
penang_r0_df$incident14 <- rollsum(penang_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_penang<- mobility %>% filter (state=="Pulau Pinang" & date >as.Date("2020-03-19")) 

#create a new varaible for state
penang<- full_join(penang_r0_df, mobility_penang, by=c("date","state"))

#add ab average
penang$average <- (penang$recreation+penang$grocery+penang$parks)/3

#################################################################################################################################
#################################################################################################################################
#filter: perak
perak <- state %>% filter(state=="Perak")

#create control parameters for MCMC
perak_r0 <- estimate_R(perak$new_cases, 
                       method="parametric_si",
                       config = make_config(list(
                         mean_si = 5.12, 
                         std_si = 1.86))#lit review
)

#create df of parameters
plot(perak_r0)
perak_r0_df<- as.data.frame(perak_r0$R[,c(1:3,5,11)])
perak_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
perak_r0_df <- perak_r0_df[,3:6]
perak_r0_df$state <- "Perak"
colnames(perak_r0_df) <- c("rt","lower","upper","date","state")
perak_r0_df$case <- perak$new_cases[8:nrow(perak)]
perak_r0_df$total_case <- perak$total_cases[8:nrow(perak)]
perak_r0_df$new_death <- perak$new_deaths[8:nrow(perak)]

perak_r0_df$active_cases_part3[4:nrow(perak_r0_df)] <- diff(perak_r0_df$total_case, lag=3)
perak_r0_df$active_cases3 <- perak_r0_df$active_cases_part3-perak_r0_df$new_death
perak_r0_df$active_cases3[1:3] <- cumsum(perak_r0_df$case[1:3])-perak_r0_df$new_death[1:3]
perak_r0_df$active_cases3[perak_r0_df$active_cases3<=0] <- 0

perak_r0_df$active_cases_part5[6:nrow(perak_r0_df)] <- diff(perak_r0_df$total_case, lag=5)
perak_r0_df$active_cases5 <- perak_r0_df$active_cases_part5-perak_r0_df$new_death
perak_r0_df$active_cases5[1:5] <- cumsum(perak_r0_df$case[1:5])-perak_r0_df$new_death[1:5]
perak_r0_df$active_cases5[perak_r0_df$active_cases5<=0] <- 0

perak_r0_df$active_cases_part9[10:nrow(perak_r0_df)] <- diff(perak_r0_df$total_case, lag=9)
perak_r0_df$active_cases9 <- perak_r0_df$active_cases_part9-perak_r0_df$new_death
perak_r0_df$active_cases9[1:9] <- cumsum(perak_r0_df$case[1:9])-perak_r0_df$new_death[1:9]
perak_r0_df$active_cases9[perak_r0_df$active_cases9<=0] <- 0

perak_r0_df <- perak_r0_df[1:nrow(perak_r0_df),]
perak_r0_df

#create moving averages
perak_r0_df <- perak_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
perak_r0_df$incident14 <- rollsum(perak_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_perak<- mobility %>% filter (state=="Perak" & date >as.Date("2020-03-19")) 

#create a new varaible for state
perak<- full_join(perak_r0_df, mobility_perak, by=c("date","state"))

#add ab average
perak$average <- (perak$recreation+perak$grocery+perak$parks)/3

#################################################################################################################################
#################################################################################################################################
#filter: selangor
selangor <- state %>% filter(state=="Selangor")

#create control parameters for MCMC
selangor_r0 <- estimate_R(selangor$new_cases, 
                          method="parametric_si",
                          config = make_config(list(
                            mean_si = 5.12, 
                            std_si = 1.86))#lit review
)

#create df of parameters
plot(selangor_r0)
selangor_r0_df<- as.data.frame(selangor_r0$R[,c(1:3,5,11)])
selangor_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)  
selangor_r0_df <- selangor_r0_df[,3:6]
selangor_r0_df$state <- "Selangor"
colnames(selangor_r0_df) <- c("rt","lower","upper","date","state")
selangor_r0_df$case <- selangor$new_cases[8:nrow(selangor)]
selangor_r0_df$total_case <- selangor$total_cases[8:nrow(selangor)]
selangor_r0_df$new_death <- selangor$new_deaths[8:nrow(selangor)]

selangor_r0_df$active_cases_part3[4:nrow(selangor_r0_df)] <- diff(selangor_r0_df$total_case, lag=3)
selangor_r0_df$active_cases3 <- selangor_r0_df$active_cases_part3-selangor_r0_df$new_death
selangor_r0_df$active_cases3[1:3] <- cumsum(selangor_r0_df$case[1:3])-selangor_r0_df$new_death[1:3]
selangor_r0_df$active_cases3[selangor_r0_df$active_cases3<=0] <- 0

selangor_r0_df$active_cases_part5[6:nrow(selangor_r0_df)] <- diff(selangor_r0_df$total_case, lag=5)
selangor_r0_df$active_cases5 <- selangor_r0_df$active_cases_part5-selangor_r0_df$new_death
selangor_r0_df$active_cases5[1:5] <- cumsum(selangor_r0_df$case[1:5])-selangor_r0_df$new_death[1:5]
selangor_r0_df$active_cases5[selangor_r0_df$active_cases5<=0] <- 0

selangor_r0_df$active_cases_part9[10:nrow(selangor_r0_df)] <- diff(selangor_r0_df$total_case, lag=9)
selangor_r0_df$active_cases9 <- selangor_r0_df$active_cases_part9-selangor_r0_df$new_death
selangor_r0_df$active_cases9[1:9] <- cumsum(selangor_r0_df$case[1:9])-selangor_r0_df$new_death[1:9]
selangor_r0_df$active_cases9[selangor_r0_df$active_cases9<=0] <- 0

selangor_r0_df <- selangor_r0_df[1:nrow(selangor_r0_df),]
selangor_r0_df

#create moving averages
selangor_r0_df <- selangor_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
selangor_r0_df$incident14 <- rollsum(selangor_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_selangor<- mobility %>% filter (state=="Selangor" & date >as.Date("2020-03-19")) 

#create a new varaible for state
selangor<- full_join(selangor_r0_df, mobility_selangor, by=c("date","state"))

#add ab average
selangor$average <- (selangor$recreation+selangor$grocery+selangor$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: kl
kl <- state %>% filter(state=="W.P. Kuala Lumpur")

#create control parameters for MCMC
kl_r0 <- estimate_R(kl$new_cases, 
                    method="parametric_si",
                    config = make_config(list(
                      mean_si = 5.12, 
                      std_si = 1.86))#lit review
)

#create df of parameters
plot(kl_r0)
kl_r0_df<- as.data.frame(kl_r0$R[,c(1:3,5,11)])
kl_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
kl_r0_df <- kl_r0_df[,3:6]
kl_r0_df$state <- "W.P. Kuala Lumpur"
colnames(kl_r0_df) <- c("rt","lower","upper","date","state")
kl_r0_df$case <- kl$new_cases[8:nrow(kl)]
kl_r0_df$total_case <- kl$total_cases[8:nrow(kl)]
kl_r0_df$new_death <- kl$new_deaths[8:nrow(kl)]

kl_r0_df$active_cases_part3[4:nrow(kl_r0_df)] <- diff(kl_r0_df$total_case, lag=3)
kl_r0_df$active_cases3 <- kl_r0_df$active_cases_part3-kl_r0_df$new_death
kl_r0_df$active_cases3[1:3] <- cumsum(kl_r0_df$case[1:3])-kl_r0_df$new_death[1:3]
kl_r0_df$active_cases3[kl_r0_df$active_cases3<=0] <- 0

kl_r0_df$active_cases_part5[6:nrow(kl_r0_df)] <- diff(kl_r0_df$total_case, lag=5)
kl_r0_df$active_cases5 <- kl_r0_df$active_cases_part5-kl_r0_df$new_death
kl_r0_df$active_cases5[1:5] <- cumsum(kl_r0_df$case[1:5])-kl_r0_df$new_death[1:5]
kl_r0_df$active_cases5[kl_r0_df$active_cases5<=0] <- 0

kl_r0_df$active_cases_part9[10:nrow(kl_r0_df)] <- diff(kl_r0_df$total_case, lag=9)
kl_r0_df$active_cases9 <- kl_r0_df$active_cases_part9-kl_r0_df$new_death
kl_r0_df$active_cases9[1:9] <- cumsum(kl_r0_df$case[1:9])-kl_r0_df$new_death[1:9]
kl_r0_df$active_cases9[kl_r0_df$active_cases9<=0] <- 0

kl_r0_df <- kl_r0_df[1:nrow(kl_r0_df),]
kl_r0_df

#create moving averages
kl_r0_df <- kl_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
kl_r0_df$incident14 <- rollsum(kl_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_kl<- mobility %>% filter (state=="W.P. Kuala Lumpur" & date >as.Date("2020-03-19")) 

#create a new varaible for state
kl<- full_join(kl_r0_df, mobility_kl, by=c("date","state"))

#add ab average
kl$average <- (kl$recreation+kl$grocery+kl$parks+kl$transit+kl$work)/5
#################################################################################################################################
#################################################################################################################################
#filter: putrajaya
putrajaya <- state %>% filter(state=="W.P. Putrajaya")

#create control parameters for MCMC
putrajaya_r0 <- estimate_R(putrajaya$new_cases, 
                           method="parametric_si",
                           config = make_config(list(
                             mean_si = 5.12, 
                             std_si = 1.86))#lit review
)

#create df of parameters
plot(putrajaya_r0)
putrajaya_r0_df<- as.data.frame(putrajaya_r0$R[,c(1:3,5,11)])
putrajaya_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
putrajaya_r0_df <- putrajaya_r0_df[,3:6]
putrajaya_r0_df$state <- "W.P. Putrajaya"
colnames(putrajaya_r0_df) <- c("rt","lower","upper","date","state")
putrajaya_r0_df$case <- putrajaya$new_cases[8:nrow(putrajaya)]
putrajaya_r0_df$total_case <- putrajaya$total_cases[8:nrow(putrajaya)]
putrajaya_r0_df$new_death <- putrajaya$new_deaths[8:nrow(putrajaya)]

putrajaya_r0_df$active_cases_part3[4:nrow(putrajaya_r0_df)] <- diff(putrajaya_r0_df$total_case, lag=3)
putrajaya_r0_df$active_cases3 <- putrajaya_r0_df$active_cases_part3-putrajaya_r0_df$new_death
putrajaya_r0_df$active_cases3[1:3] <- cumsum(putrajaya_r0_df$case[1:3])-putrajaya_r0_df$new_death[1:3]
putrajaya_r0_df$active_cases3[putrajaya_r0_df$active_cases3<=0] <- 0

putrajaya_r0_df$active_cases_part5[6:nrow(putrajaya_r0_df)] <- diff(putrajaya_r0_df$total_case, lag=5)
putrajaya_r0_df$active_cases5 <- putrajaya_r0_df$active_cases_part5-putrajaya_r0_df$new_death
putrajaya_r0_df$active_cases5[1:5] <- cumsum(putrajaya_r0_df$case[1:5])-putrajaya_r0_df$new_death[1:5]
putrajaya_r0_df$active_cases5[putrajaya_r0_df$active_cases5<=0] <- 0

putrajaya_r0_df$active_cases_part9[10:nrow(putrajaya_r0_df)] <- diff(putrajaya_r0_df$total_case, lag=9)
putrajaya_r0_df$active_cases9 <- putrajaya_r0_df$active_cases_part9-putrajaya_r0_df$new_death
putrajaya_r0_df$active_cases9[1:9] <- cumsum(putrajaya_r0_df$case[1:9])-putrajaya_r0_df$new_death[1:9]
putrajaya_r0_df$active_cases9[putrajaya_r0_df$active_cases9<=0] <- 0

putrajaya_r0_df <- putrajaya_r0_df[1:nrow(putrajaya_r0_df),]
putrajaya_r0_df

#create moving averages
putrajaya_r0_df <- putrajaya_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
putrajaya_r0_df$incident14 <- rollsum(putrajaya_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_putrajaya<- mobility %>% filter (state=="W.P. Putrajaya" & date >as.Date("2020-03-19")) 

#create a new varaible for state
putrajaya<- full_join(putrajaya_r0_df, mobility_putrajaya, by=c("date","state"))

#add ab average
putrajaya$average <- (putrajaya$recreation+putrajaya$grocery+putrajaya$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: negeri
negeri<- state %>% filter(state=="Negeri Sembilan")

#create control parameters for MCMC
negeri_r0 <- estimate_R(negeri$new_cases, 
                        method="parametric_si",
                        config = make_config(list(
                          mean_si = 5.12, 
                          std_si = 1.86))#lit review
)

#create df of parameters
plot(negeri_r0)
negeri_r0_df<- as.data.frame(negeri_r0$R[,c(1:3,5,11)])
negeri_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
negeri_r0_df <- negeri_r0_df[,3:6]
negeri_r0_df$state <- "Negeri Sembilan"
colnames(negeri_r0_df) <- c("rt","lower","upper","date","state")
negeri_r0_df$case <- negeri$new_cases[8:nrow(negeri)]
negeri_r0_df$total_case <- negeri$total_cases[8:nrow(negeri)]
negeri_r0_df$new_death <- negeri$new_deaths[8:nrow(negeri)]

negeri_r0_df$active_cases_part3[4:nrow(negeri_r0_df)] <- diff(negeri_r0_df$total_case, lag=3)
negeri_r0_df$active_cases3 <- negeri_r0_df$active_cases_part3-negeri_r0_df$new_death
negeri_r0_df$active_cases3[1:3] <- cumsum(negeri_r0_df$case[1:3])-negeri_r0_df$new_death[1:3]
negeri_r0_df$active_cases3[negeri_r0_df$active_cases3<=0] <- 0

negeri_r0_df$active_cases_part5[6:nrow(negeri_r0_df)] <- diff(negeri_r0_df$total_case, lag=5)
negeri_r0_df$active_cases5 <- negeri_r0_df$active_cases_part5-negeri_r0_df$new_death
negeri_r0_df$active_cases5[1:5] <- cumsum(negeri_r0_df$case[1:5])-negeri_r0_df$new_death[1:5]
negeri_r0_df$active_cases5[negeri_r0_df$active_cases5<=0] <- 0

negeri_r0_df$active_cases_part9[10:nrow(negeri_r0_df)] <- diff(negeri_r0_df$total_case, lag=9)
negeri_r0_df$active_cases9 <- negeri_r0_df$active_cases_part9-negeri_r0_df$new_death
negeri_r0_df$active_cases9[1:9] <- cumsum(negeri_r0_df$case[1:9])-negeri_r0_df$new_death[1:9]
negeri_r0_df$active_cases9[negeri_r0_df$active_cases9<=0] <- 0

negeri_r0_df <- negeri_r0_df[1:nrow(negeri_r0_df),]
negeri_r0_df

#create moving averages
negeri_r0_df <- negeri_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
negeri_r0_df$incident14 <- rollsum(negeri_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_negeri<- mobility %>% filter (state=="Negeri Sembilan" & date >as.Date("2020-03-19")) 

#create a new varaible for state
negeri<- full_join(negeri_r0_df, mobility_negeri, by=c("date","state"))

#add ab average
negeri$average <- (negeri$recreation+negeri$grocery+negeri$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: melaka
melaka<- state %>% filter(state=="Melaka")

#create control parameters for MCMC
melaka_r0 <- estimate_R(melaka$new_cases, 
                        method="parametric_si",
                        config = make_config(list(
                          mean_si = 5.12, 
                          std_si = 1.86))#lit review
)

#create df of parameters
plot(melaka_r0)
melaka_r0_df<- as.data.frame(melaka_r0$R[,c(1:3,5,11)])
melaka_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
melaka_r0_df <- melaka_r0_df[,3:6]
melaka_r0_df$state <- "Melaka"
colnames(melaka_r0_df) <- c("rt","lower","upper","date","state")
melaka_r0_df$case <- melaka$new_cases[8:nrow(melaka)]
melaka_r0_df$total_case <- melaka$total_cases[8:nrow(melaka)]
melaka_r0_df$new_death <- melaka$new_deaths[8:nrow(melaka)]

melaka_r0_df$active_cases_part3[4:nrow(melaka_r0_df)] <- diff(melaka_r0_df$total_case, lag=3)
melaka_r0_df$active_cases3 <- melaka_r0_df$active_cases_part3-melaka_r0_df$new_death
melaka_r0_df$active_cases3[1:3] <- cumsum(melaka_r0_df$case[1:3])-melaka_r0_df$new_death[1:3]
melaka_r0_df$active_cases3[melaka_r0_df$active_cases3<=0] <- 0

melaka_r0_df$active_cases_part5[6:nrow(melaka_r0_df)] <- diff(melaka_r0_df$total_case, lag=5)
melaka_r0_df$active_cases5 <- melaka_r0_df$active_cases_part5-melaka_r0_df$new_death
melaka_r0_df$active_cases5[1:5] <- cumsum(melaka_r0_df$case[1:5])-melaka_r0_df$new_death[1:5]
melaka_r0_df$active_cases5[melaka_r0_df$active_cases5<=0] <- 0

melaka_r0_df$active_cases_part9[10:nrow(melaka_r0_df)] <- diff(melaka_r0_df$total_case, lag=9)
melaka_r0_df$active_cases9 <- melaka_r0_df$active_cases_part9-melaka_r0_df$new_death
melaka_r0_df$active_cases9[1:9] <- cumsum(melaka_r0_df$case[1:9])-melaka_r0_df$new_death[1:9]
melaka_r0_df$active_cases9[melaka_r0_df$active_cases9<=0] <- 0

melaka_r0_df <- melaka_r0_df[1:nrow(melaka_r0_df),]
melaka_r0_df

#create moving averages
melaka_r0_df <- melaka_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
melaka_r0_df$incident14 <- rollsum(melaka_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_melaka<- mobility %>% filter (state=="Melaka" & date >as.Date("2020-03-19")) 

#create a new varaible for state
melaka<- full_join(melaka_r0_df, mobility_melaka, by=c("date","state"))

#add ab average
melaka$average <- (melaka$recreation+melaka$grocery+melaka$park)/3

#################################################################################################################################
#################################################################################################################################
#filter: johor
johor<- state %>% filter(state=="Johor")

#create control parameters for MCMC
johor_r0 <- estimate_R(johor$new_cases, 
                       method="parametric_si",
                       config = make_config(list(
                         mean_si = 5.12, 
                         std_si = 1.86))#lit review
)

#create df of parameters
plot(johor_r0)
johor_r0_df<- as.data.frame(johor_r0$R[,c(1:3,5,11)])
johor_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day) 
johor_r0_df <- johor_r0_df[,3:6]
johor_r0_df$state <- "Johor"
colnames(johor_r0_df) <- c("rt","lower","upper","date","state")
johor_r0_df$case <- johor$new_cases[8:nrow(johor)]
johor_r0_df$total_case <- johor$total_cases[8:nrow(johor)]
johor_r0_df$new_death <- johor$new_deaths[8:nrow(johor)]

johor_r0_df$active_cases_part3[4:nrow(johor_r0_df)] <- diff(johor_r0_df$total_case, lag=3)
johor_r0_df$active_cases3 <- johor_r0_df$active_cases_part3-johor_r0_df$new_death
johor_r0_df$active_cases3[1:3] <- cumsum(johor_r0_df$case[1:3])-johor_r0_df$new_death[1:3]
johor_r0_df$active_cases3[johor_r0_df$active_cases3<=0] <- 0

johor_r0_df$active_cases_part5[6:nrow(johor_r0_df)] <- diff(johor_r0_df$total_case, lag=5)
johor_r0_df$active_cases5 <- johor_r0_df$active_cases_part5-johor_r0_df$new_death
johor_r0_df$active_cases5[1:5] <- cumsum(johor_r0_df$case[1:5])-johor_r0_df$new_death[1:5]
johor_r0_df$active_cases5[johor_r0_df$active_cases5<=0] <- 0

johor_r0_df$active_cases_part9[10:nrow(johor_r0_df)] <- diff(johor_r0_df$total_case, lag=9)
johor_r0_df$active_cases9 <- johor_r0_df$active_cases_part9-johor_r0_df$new_death
johor_r0_df$active_cases9[1:9] <- cumsum(johor_r0_df$case[1:9])-johor_r0_df$new_death[1:9]
johor_r0_df$active_cases9[johor_r0_df$active_cases9<=0] <- 0

johor_r0_df <- johor_r0_df[1:nrow(johor_r0_df),]
johor_r0_df

#create moving averages
johor_r0_df <- johor_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))


#create a 14-day moving incidence rate
johor_r0_df$incident14 <- rollsum(johor_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_johor<- mobility %>% filter (state=="Johor" & date >as.Date("2020-03-19")) 

#create a new varaible for state
johor<- full_join(johor_r0_df, mobility_johor, by=c("date","state"))

#add ab average
johor$average <- (johor$recreation+johor$grocery+johor$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: pahanag
pahang<- state %>% filter(state=="Pahang")

#create control parameters for MCMC
pahang_r0 <- estimate_R(pahang$new_cases, 
                        method="parametric_si",
                        config = make_config(list(
                          mean_si = 5.12, 
                          std_si = 1.86))#lit review
)

#create df of parameters
plot(pahang_r0)
pahang_r0_df<- as.data.frame(pahang_r0$R[,c(1:3,5,11)])
pahang_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
pahang_r0_df <- pahang_r0_df[,3:6]
pahang_r0_df$state <- "Pahang"
colnames(pahang_r0_df) <- c("rt","lower","upper","date","state")
pahang_r0_df$case <- pahang$new_cases[8:nrow(pahang)]
pahang_r0_df$total_case <- pahang$total_cases[8:nrow(pahang)]
pahang_r0_df$new_death <- pahang$new_deaths[8:nrow(pahang)]

pahang_r0_df$active_cases_part3[4:nrow(pahang_r0_df)] <- diff(pahang_r0_df$total_case, lag=3)
pahang_r0_df$active_cases3 <- pahang_r0_df$active_cases_part3-pahang_r0_df$new_death
pahang_r0_df$active_cases3[1:3] <- cumsum(pahang_r0_df$case[1:3])-pahang_r0_df$new_death[1:3]
pahang_r0_df$active_cases3[pahang_r0_df$active_cases3<=0] <- 0

pahang_r0_df$active_cases_part5[6:nrow(pahang_r0_df)] <- diff(pahang_r0_df$total_case, lag=5)
pahang_r0_df$active_cases5 <- pahang_r0_df$active_cases_part5-pahang_r0_df$new_death
pahang_r0_df$active_cases5[1:5] <- cumsum(pahang_r0_df$case[1:5])-pahang_r0_df$new_death[1:5]
pahang_r0_df$active_cases5[pahang_r0_df$active_cases5<=0] <- 0

pahang_r0_df$active_cases_part9[10:nrow(pahang_r0_df)] <- diff(pahang_r0_df$total_case, lag=9)
pahang_r0_df$active_cases9 <- pahang_r0_df$active_cases_part9-pahang_r0_df$new_death
pahang_r0_df$active_cases9[1:9] <- cumsum(pahang_r0_df$case[1:9])-pahang_r0_df$new_death[1:9]
pahang_r0_df$active_cases9[pahang_r0_df$active_cases9<=0] <- 0

pahang_r0_df <- pahang_r0_df[1:nrow(pahang_r0_df),]
pahang_r0_df

#create moving averages
pahang_r0_df <- pahang_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
pahang_r0_df$incident14 <- rollsum(pahang_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_pahang<- mobility %>% filter (state=="Pahang" & date >as.Date("2020-03-19")) 

#create a new varaible for state
pahang<- full_join(pahang_r0_df, mobility_pahang, by=c("date","state"))

#add ab average
pahang$average <- (pahang$recreation+pahang$grocery+pahang$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: terengganu
terengganu<- state %>% filter(state=="Terengganu")

#create control parameters for MCMC
terengganu_r0 <- estimate_R(terengganu$new_cases, 
                            method="parametric_si",
                            config = make_config(list(
                              mean_si = 5.12, 
                              std_si = 1.86))#lit review
)

#create df of parameters
plot(terengganu_r0)
terengganu_r0_df<- as.data.frame(terengganu_r0$R[,c(1:3,5,11)])
terengganu_r0_df$date <- seq(from=as.Date("2020-03-20"),to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
terengganu_r0_df <- terengganu_r0_df[,3:6]
terengganu_r0_df$state <- "Terengganu"
colnames(terengganu_r0_df) <- c("rt","lower","upper","date","state")
terengganu_r0_df$case <- terengganu$new_cases[8:nrow(terengganu)]
terengganu_r0_df$total_case <- terengganu$total_cases[8:nrow(terengganu)]
terengganu_r0_df$new_death <- terengganu$new_deaths[8:nrow(terengganu)]

terengganu_r0_df$active_cases_part3[4:nrow(terengganu_r0_df)] <- diff(terengganu_r0_df$total_case, lag=3)
terengganu_r0_df$active_cases3 <- terengganu_r0_df$active_cases_part3-terengganu_r0_df$new_death
terengganu_r0_df$active_cases3[1:3] <- cumsum(terengganu_r0_df$case[1:3])-terengganu_r0_df$new_death[1:3]
terengganu_r0_df$active_cases3[terengganu_r0_df$active_cases3<=0] <- 0

terengganu_r0_df$active_cases_part5[6:nrow(terengganu_r0_df)] <- diff(terengganu_r0_df$total_case, lag=5)
terengganu_r0_df$active_cases5 <- terengganu_r0_df$active_cases_part5-terengganu_r0_df$new_death
terengganu_r0_df$active_cases5[1:5] <- cumsum(terengganu_r0_df$case[1:5])-terengganu_r0_df$new_death[1:5]
terengganu_r0_df$active_cases5[terengganu_r0_df$active_cases5<=0] <- 0

terengganu_r0_df$active_cases_part9[10:nrow(terengganu_r0_df)] <- diff(terengganu_r0_df$total_case, lag=9)
terengganu_r0_df$active_cases9 <- terengganu_r0_df$active_cases_part9-terengganu_r0_df$new_death
terengganu_r0_df$active_cases9[1:9] <- cumsum(terengganu_r0_df$case[1:9])-terengganu_r0_df$new_death[1:9]
terengganu_r0_df$active_cases9[terengganu_r0_df$active_cases9<=0] <- 0

terengganu_r0_df <- terengganu_r0_df[1:nrow(terengganu_r0_df),]
terengganu_r0_df

#create moving averages
terengganu_r0_df <- terengganu_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
terengganu_r0_df$incident14 <- rollsum(terengganu_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_terengganu<- mobility %>% filter (state=="Terengganu" & date >as.Date("2020-03-19")) 

#create a new varaible for state
terengganu<- full_join(terengganu_r0_df, mobility_terengganu, by=c("date","state"))

#add ab average
terengganu$average <- (terengganu$recreation+terengganu$grocery+terengganu$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: kelantan
kelantan<- state %>% filter(state=="Kelantan")

#create control parameters for MCMC
kelantan_r0 <- estimate_R(kelantan$new_cases, 
                          method="parametric_si",
                          config = make_config(list(
                            mean_si = 5.12, 
                            std_si = 1.86))#lit review
)

#create df of parameters
plot(kelantan_r0)
kelantan_r0_df<- as.data.frame(kelantan_r0$R[,c(1:3,5,11)])
kelantan_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
kelantan_r0_df <- kelantan_r0_df[,3:6]
kelantan_r0_df$state <- "Kelantan"
colnames(kelantan_r0_df) <- c("rt","lower","upper","date","state")
kelantan_r0_df$case <- kelantan$new_cases[8:nrow(kelantan)]
kelantan_r0_df$total_case <- kelantan$total_cases[8:nrow(kelantan)]
kelantan_r0_df$new_death <- kelantan$new_deaths[8:nrow(kelantan)]

kelantan_r0_df$active_cases_part3[4:nrow(kelantan_r0_df)] <- diff(kelantan_r0_df$total_case, lag=3)
kelantan_r0_df$active_cases3 <- kelantan_r0_df$active_cases_part3-kelantan_r0_df$new_death
kelantan_r0_df$active_cases3[1:3] <- cumsum(kelantan_r0_df$case[1:3])-kelantan_r0_df$new_death[1:3]
kelantan_r0_df$active_cases3[kelantan_r0_df$active_cases3<=0] <- 0

kelantan_r0_df$active_cases_part5[6:nrow(kelantan_r0_df)] <- diff(kelantan_r0_df$total_case, lag=5)
kelantan_r0_df$active_cases5 <- kelantan_r0_df$active_cases_part5-kelantan_r0_df$new_death
kelantan_r0_df$active_cases5[1:5] <- cumsum(kelantan_r0_df$case[1:5])-kelantan_r0_df$new_death[1:5]
kelantan_r0_df$active_cases5[kelantan_r0_df$active_cases5<=0] <- 0

kelantan_r0_df$active_cases_part9[10:nrow(kelantan_r0_df)] <- diff(kelantan_r0_df$total_case, lag=9)
kelantan_r0_df$active_cases9 <- kelantan_r0_df$active_cases_part9-kelantan_r0_df$new_death
kelantan_r0_df$active_cases9[1:9] <- cumsum(kelantan_r0_df$case[1:9])-kelantan_r0_df$new_death[1:9]
kelantan_r0_df$active_cases9[kelantan_r0_df$active_cases9<=0] <- 0

kelantan_r0_df <- kelantan_r0_df[1:nrow(kelantan_r0_df),]
kelantan_r0_df

#create moving averages
kelantan_r0_df <- kelantan_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
kelantan_r0_df$incident14 <- rollsum(kelantan_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_kelantan<- mobility %>% filter (state=="Kelantan" & date >as.Date("2020-03-19")) 

#create a new varaible for state
kelantan<- full_join(kelantan_r0_df, mobility_kelantan, by=c("date","state"))

#add ab average
kelantan$average <- (kelantan$recreation+kelantan$grocery+kelantan$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: sabah
sabah<- state %>% filter(state=="Sabah")

#create control parameters for MCMC
sabah_r0 <- estimate_R(sabah$new_cases, 
                       method="parametric_si",
                       config = make_config(list(
                         mean_si = 5.12, 
                         std_si = 1.86))#lit review
)

#create df of parameters
plot(sabah_r0)
sabah_r0_df<- as.data.frame(sabah_r0$R[,c(1:3,5,11)])
sabah_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
sabah_r0_df <- sabah_r0_df[,3:6]
sabah_r0_df$state <- "Sabah"
colnames(sabah_r0_df) <- c("rt","lower","upper","date","state")
sabah_r0_df$case <- sabah$new_cases[8:nrow(sabah)]
sabah_r0_df$total_case <- sabah$total_cases[8:nrow(sabah)]
sabah_r0_df$new_death <- sabah$new_deaths[8:nrow(sabah)]

sabah_r0_df$active_cases_part3[4:nrow(sabah_r0_df)] <- diff(sabah_r0_df$total_case, lag=3)
sabah_r0_df$active_cases3 <- sabah_r0_df$active_cases_part3-sabah_r0_df$new_death
sabah_r0_df$active_cases3[1:3] <- cumsum(sabah_r0_df$case[1:3])-sabah_r0_df$new_death[1:3]
sabah_r0_df$active_cases3[sabah_r0_df$active_cases3<=0] <- 0

sabah_r0_df$active_cases_part5[6:nrow(sabah_r0_df)] <- diff(sabah_r0_df$total_case, lag=5)
sabah_r0_df$active_cases5 <- sabah_r0_df$active_cases_part5-sabah_r0_df$new_death
sabah_r0_df$active_cases5[1:5] <- cumsum(sabah_r0_df$case[1:5])-sabah_r0_df$new_death[1:5]
sabah_r0_df$active_cases5[sabah_r0_df$active_cases5<=0] <- 0

sabah_r0_df$active_cases_part9[10:nrow(sabah_r0_df)] <- diff(sabah_r0_df$total_case, lag=9)
sabah_r0_df$active_cases9 <- sabah_r0_df$active_cases_part9-sabah_r0_df$new_death
sabah_r0_df$active_cases9[1:9] <- cumsum(sabah_r0_df$case[1:9])-sabah_r0_df$new_death[1:9]
sabah_r0_df$active_cases9[sabah_r0_df$active_cases9<=0] <- 0

sabah_r0_df <- sabah_r0_df[1:nrow(sabah_r0_df),]
sabah_r0_df


#create moving averages
sabah_r0_df <- sabah_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
sabah_r0_df$incident14 <- rollsum(sabah_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_sabah<- mobility %>% filter (state=="Sabah" & date >as.Date("2020-03-19")) 

#create a new varaible for state
sabah<- full_join(sabah_r0_df, mobility_sabah, by=c("date","state"))

#add ab average
sabah$average <- (sabah$recreation+sabah$grocery+sabah$parks)/3

#################################################################################################################################
#################################################################################################################################
#filter: sarawak
sarawak<- state %>% filter(state=="Sarawak")

#create control parameters for MCMC
sarawak_r0 <- estimate_R(sarawak$new_cases, 
                         method="parametric_si",
                         config = make_config(list(
                           mean_si = 5.12, 
                           std_si = 1.86))#lit review
)

#create df of parameters
plot(sarawak_r0)
sarawak_r0_df<- as.data.frame(sarawak_r0$R[,c(1:3,5,11)])
sarawak_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day)
sarawak_r0_df <- sarawak_r0_df[,3:6]
sarawak_r0_df$state <- "Sarawak"
colnames(sarawak_r0_df) <- c("rt","lower","upper","date","state")
sarawak_r0_df$case <- sarawak$new_cases[8:nrow(sarawak)]
sarawak_r0_df$total_case <- sarawak$total_cases[8:nrow(sarawak)]
sarawak_r0_df$new_death <- sarawak$new_deaths[8:nrow(sarawak)]

sarawak_r0_df$active_cases_part3[4:nrow(sarawak_r0_df)] <- diff(sarawak_r0_df$total_case, lag=3)
sarawak_r0_df$active_cases3 <- sarawak_r0_df$active_cases_part3-sarawak_r0_df$new_death
sarawak_r0_df$active_cases3[1:3] <- cumsum(sarawak_r0_df$case[1:3])-sarawak_r0_df$new_death[1:3]
sarawak_r0_df$active_cases3[sarawak_r0_df$active_cases3<=0] <- 0

sarawak_r0_df$active_cases_part5[6:nrow(sarawak_r0_df)] <- diff(sarawak_r0_df$total_case, lag=5)
sarawak_r0_df$active_cases5 <- sarawak_r0_df$active_cases_part5-sarawak_r0_df$new_death
sarawak_r0_df$active_cases5[1:5] <- cumsum(sarawak_r0_df$case[1:5])-sarawak_r0_df$new_death[1:5]
sarawak_r0_df$active_cases5[sarawak_r0_df$active_cases5<=0] <- 0

sarawak_r0_df$active_cases_part9[10:nrow(sarawak_r0_df)] <- diff(sarawak_r0_df$total_case, lag=9)
sarawak_r0_df$active_cases9 <- sarawak_r0_df$active_cases_part9-sarawak_r0_df$new_death
sarawak_r0_df$active_cases9[1:9] <- cumsum(sarawak_r0_df$case[1:9])-sarawak_r0_df$new_death[1:9]
sarawak_r0_df$active_cases9[sarawak_r0_df$active_cases9<=0] <- 0

sarawak_r0_df <- sarawak_r0_df[1:nrow(sarawak_r0_df),]
sarawak_r0_df

#create moving averages
sarawak_r0_df <- sarawak_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
sarawak_r0_df$incident14 <- rollsum(sarawak_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_sarawak<- mobility %>% filter (state=="Sarawak" & date >as.Date("2020-03-19")) 

#create a new varaible for state
sarawak<- full_join(sarawak_r0_df, mobility_sarawak, by=c("date","state"))

#add ab average
sarawak$average <- (sarawak$recreation+sarawak$grocery+sarawak$parks)/3
#################################################################################################################################
#################################################################################################################################
#filter: labuan
labuan<- state %>% filter(state=="W.P. Labuan")

#create control parameters for MCMC
labuan_r0 <- estimate_R(labuan$new_cases, 
                        method="parametric_si",
                        config = make_config(list(
                          mean_si = 5.12, 
                          std_si = 1.86))#lit review
)

#create df of parameters
plot(labuan_r0)
labuan_r0_df<- as.data.frame(labuan_r0$R[,c(1:3,5,11)])
labuan_r0_df$date <- seq(from=as.Date("2020-03-20"), to=as.Date(Sys.Date()),by=1) # TODO: if elapsed by a day -1 from the date (-1 for each elapsed day) 
labuan_r0_df <- labuan_r0_df[,3:6]
labuan_r0_df$state <- "W.P. Labuan"
colnames(labuan_r0_df) <- c("rt","lower","upper","date","state")
labuan_r0_df$case <- labuan$new_cases[8:nrow(labuan)]
labuan_r0_df$total_case <- labuan$total_cases[8:nrow(labuan)]
labuan_r0_df$new_death <- labuan$new_deaths[8:nrow(labuan)]

labuan_r0_df$active_cases_part3[4:nrow(labuan_r0_df)] <- diff(labuan_r0_df$total_case, lag=3)
labuan_r0_df$active_cases3 <- labuan_r0_df$active_cases_part3-labuan_r0_df$new_death
labuan_r0_df$active_cases3[1:3] <- cumsum(labuan_r0_df$case[1:3])-labuan_r0_df$new_death[1:3]
labuan_r0_df$active_cases3[labuan_r0_df$active_cases3<=0] <- 0

labuan_r0_df$active_cases_part5[6:nrow(labuan_r0_df)] <- diff(labuan_r0_df$total_case, lag=5)
labuan_r0_df$active_cases5 <- labuan_r0_df$active_cases_part5-labuan_r0_df$new_death
labuan_r0_df$active_cases5[1:5] <- cumsum(labuan_r0_df$case[1:5])-labuan_r0_df$new_death[1:5]
labuan_r0_df$active_cases5[labuan_r0_df$active_cases5<=0] <- 0

labuan_r0_df$active_cases_part9[10:nrow(labuan_r0_df)] <- diff(labuan_r0_df$total_case, lag=9)
labuan_r0_df$active_cases9 <- labuan_r0_df$active_cases_part9-labuan_r0_df$new_death
labuan_r0_df$active_cases9[1:9] <- cumsum(labuan_r0_df$case[1:9])-labuan_r0_df$new_death[1:9]
labuan_r0_df$active_cases9[labuan_r0_df$active_cases9<=0] <- 0

labuan_r0_df <- labuan_r0_df[1:nrow(labuan_r0_df),]
labuan_r0_df


#create moving averages
labuan_r0_df <- labuan_r0_df %>%
  mutate(daily_ma01 = rollmean(case, k = 7, fill = "extend"))

#create a 14-day moving incidence rate
labuan_r0_df$incident14 <- rollsum(labuan_r0_df$case,k=14,fill=NA, align="right")

#average mobility of 5 scores for each state`
mobility_labuan<- mobility %>% filter (state=="W.P. Labuan" & date >as.Date("2020-03-19")) 

#create a new varaible for state
labuan<- full_join(labuan_r0_df, mobility_labuan, by=c("date","state"))

#add ab average
labuan$average <- (labuan$recreation+labuan$grocery+labuan$parks)/3

```


```{r, include =FALSE}
#lets then include the state data for health systems and calculate the incidence
#load the state data
state_data_v2 <- read_excel("P:/COVID-19/R0 Malaysia/data/population_healthcapacity/state_data_v3.xlsx", 
    col_types = c("text", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric", "numeric", "numeric", 
        "numeric","numeric"))

#calculate the cumulative number of cases
perlis$cumsum <- cumsum(perlis$case)
kedah$cumsum <- cumsum(kedah$case)
penang$cumsum <- cumsum(penang$case)
perak$cumsum <- cumsum(perak$ case)
selangor$cumsum <- cumsum(selangor$case)
kl$cumsum <- cumsum(kl$case)
putrajaya$cumsum <- cumsum(putrajaya$case)
melaka$cumsum <- cumsum(melaka$case)
negeri$cumsum <- cumsum(negeri$case)
johor$cumsum <- cumsum(johor$case)
pahang$cumsum <- cumsum(pahang$case)
terengganu$cumsum <- cumsum(terengganu$case)
kelantan$cumsum <- cumsum(kelantan$case)
sabah$cumsum <- cumsum(sabah$case)
sarawak$cumsum <- cumsum(sarawak$case)
labuan$cumsum <- cumsum(labuan$case)

#lets calculate the incidence by state
perlis$incidence <- round((perlis$cumsum /state_data_v2$population_new[state_data_v2$state=="Perlis"])*100000,2)
kedah$incidence <- round((kedah$cumsum /state_data_v2$population_new[state_data_v2$state=="Kedah"])*100000,2)
penang$incidence <- round((penang$cumsum /state_data_v2$population_new[state_data_v2$state=="Pulau Pinang"])*100000,2)
perak$incidence <- round((perak$cumsum /state_data_v2$population_new[state_data_v2$state=="Perak"])*100000,2)
selangor$incidence <- round((selangor$cumsum /state_data_v2$population_new[state_data_v2$state=="Selangor"])*100000,2)
kl$incidence <- round((kl$cumsum /state_data_v2$population_new[state_data_v2$state=="W.P. Kuala Lumpur"])*100000,2)
putrajaya$incidence <- round((putrajaya$cumsum /state_data_v2$population_new[state_data_v2$state=="W.P. Putrajaya"])*100000,2)
melaka$incidence <- round((melaka$cumsum /state_data_v2$population_new[state_data_v2$state=="Melaka"])*100000,2)
negeri$incidence <- round((negeri$cumsum /state_data_v2$population_new[state_data_v2$state=="Negeri Sembilan"])*100000,2)
johor$incidence <- round((johor$cumsum /state_data_v2$population_new[state_data_v2$state=="Johor"])*100000,2)
pahang$incidence <- round((pahang$cumsum /state_data_v2$population_new[state_data_v2$state=="Pahang"])*100000,2)
terengganu$incidence <- round((terengganu$cumsum /state_data_v2$population_new[state_data_v2$state=="Terengganu"])*100000,2)
kelantan$incidence <- round((kelantan$cumsum /state_data_v2$population_new[state_data_v2$state=="Kelantan"])*100000,2)
sabah$incidence <- round((sabah$cumsum /state_data_v2$population_new[state_data_v2$state=="Sabah"])*100000,2)
sarawak$incidence <- round((sarawak$cumsum /state_data_v2$population_new[state_data_v2$state=="Sarawak"])*100000,2)
labuan$incidence <- round((labuan$cumsum /state_data_v2$population_new[state_data_v2$state=="W.P. Labuan"])*100000,2)

#add 14-day incidence by states
perlis$incidence14_rate <- round((perlis$incident14/state_data_v2$population_new[state_data_v2$state=="Perlis"])*100000,2)
kedah$incidence14_rate <- round((kedah$incident14 /state_data_v2$population_new[state_data_v2$state=="Kedah"])*100000,2)
penang$incidence14_rate <- round((penang$incident14 /state_data_v2$population_new[state_data_v2$state=="Pulau Pinang"])*100000,2)
perak$incidence14_rate <- round((perak$incident14 /state_data_v2$population_new[state_data_v2$state=="Perak"])*100000,2)
selangor$incidence14_rate <- round((selangor$incident14 /state_data_v2$population_new[state_data_v2$state=="Selangor"])*100000,2)
kl$incidence14_rate <- round((kl$incident14 /state_data_v2$population_new[state_data_v2$state=="W.P. Kuala Lumpur"])*100000,2)
putrajaya$incidence14_rate <- round((putrajaya$incident14 /state_data_v2$population_new[state_data_v2$state=="W.P. Putrajaya"])*100000,2)
melaka$incidence14_rate <- round((melaka$incident14 /state_data_v2$population_new[state_data_v2$state=="Melaka"])*100000,2)
negeri$incidence14_rate <- round((negeri$incident14 /state_data_v2$population_new[state_data_v2$state=="Negeri Sembilan"])*100000,2)
johor$incidence14_rate <- round((johor$incident14 /state_data_v2$population_new[state_data_v2$state=="Johor"])*100000,2)
pahang$incidence14_rate <- round((pahang$incident14 /state_data_v2$population_new[state_data_v2$state=="Pahang"])*100000,2)
terengganu$incidence14_rate <- round((terengganu$incident14 /state_data_v2$population_new[state_data_v2$state=="Terengganu"])*100000,2)
kelantan$incidence14_rate <- round((kelantan$incident14 /state_data_v2$population_new[state_data_v2$state=="Kelantan"])*100000,2)
sabah$incidence14_rate <- round((sabah$incident14 /state_data_v2$population_new[state_data_v2$state=="Sabah"])*100000,2)
sarawak$incidence14_rate <- round((sarawak$incident14 /state_data_v2$population_new[state_data_v2$state=="Sarawak"])*100000,2)
labuan$incidence14_rate <- round((labuan$incident14 /state_data_v2$population_new[state_data_v2$state=="W.P. Labuan"])*100000,2)

#add in a column for hospitals and icu beds
perlis$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Perlis"]
kedah$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Kedah"]
penang$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Pulau Pinang"]
perak$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Perak"]
selangor$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Selangor_28122020"]
kl$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="W.P. Kuala Lumpur__28122020"]
putrajaya$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="W.P. Putrajaya"]
melaka$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Melaka"]
negeri$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Negeri Sembilan"]
johor$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Johor"]
pahang$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Pahang"]
kelantan$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Kelantan"]
terengganu$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Terengganu"]
sabah$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Sabah_09012021"]
sarawak$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="Sarawak"]
labuan$hbed <- state_data_v2$total_gov_beds[state_data_v2$state=="W.P. Labuan_29102020"]

#add in a column for percentage of beds left
perlis$bed_perc3 <- (perlis$active_cases3/(perlis$hbed*0.2))*100
kedah$bed_perc3 <- (kedah$active_cases3/(kedah$hbed*0.2))*100
penang$bed_perc3 <- (penang$active_cases3/(penang$hbed*0.2))*100
perak$bed_perc3 <- (perak$active_cases3/(perak$hbed*0.2))*100
selangor$bed_perc3 <- (selangor$active_cases3/(selangor$hbed*0.2))*100
kl$bed_perc3 <- (kl$active_cases3/(kl$hbed*0.2))*100
putrajaya$bed_perc3 <- (putrajaya$active_cases3/(putrajaya$hbed*0.2))*100
melaka$bed_perc3 <- (melaka$active_cases3/(melaka$hbed*0.2))*100
negeri$bed_perc3 <- (negeri$active_cases3/(negeri$hbed*0.2))*100
johor$bed_perc3 <- (johor$active_cases3/(johor$hbed*0.2))*100
pahang$bed_perc3 <- (pahang$active_cases3/(pahang$hbed*0.2))*100
kelantan$bed_perc3 <- (kelantan$active_cases3/(kelantan$hbed*0.2))*100
terengganu$bed_perc3 <- (terengganu$active_cases3/(terengganu$hbed*0.2))*100
sabah$bed_perc3 <- (sabah$active_cases3/sabah$hbed)*100
sarawak$bed_perc3 <- (sarawak$active_cases3/(sarawak$hbed*0.2))*100
labuan$bed_perc3 <- (labuan$active_cases3/labuan$hbed)*100


perlis$bed_perc5 <- (perlis$active_cases5/(perlis$hbed*0.2))*100
kedah$bed_perc5 <- (kedah$active_cases5/(kedah$hbed*0.2))*100
penang$bed_perc5 <- (penang$active_cases5/(penang$hbed*0.2))*100
perak$bed_perc5 <- (perak$active_cases5/(perak$hbed*0.2))*100
selangor$bed_perc5 <- (selangor$active_cases5/(selangor$hbed*0.2))*100
kl$bed_perc5 <- (kl$active_cases5/(kl$hbed*0.2))*100
putrajaya$bed_perc5 <- (putrajaya$active_cases5/(putrajaya$hbed*0.2))*100
melaka$bed_perc5 <- (melaka$active_cases5/(melaka$hbed*0.2))*100
negeri$bed_perc5 <- (negeri$active_cases5/(negeri$hbed*0.2))*100
johor$bed_perc5 <- (johor$active_cases5/(johor$hbed*0.2))*100
pahang$bed_perc5 <- (pahang$active_cases5/(pahang$hbed*0.2))*100
kelantan$bed_perc5 <- (kelantan$active_cases5/(kelantan$hbed*0.2))*100
terengganu$bed_perc5 <- (terengganu$active_cases5/(terengganu$hbed*0.2))*100
sabah$bed_perc5 <- (sabah$active_cases5/sabah$hbed)*100
sarawak$bed_perc5 <- (sarawak$active_cases5/(sarawak$hbed*0.2))*100
labuan$bed_perc5 <- (labuan$active_cases5/labuan$hbed)*100

perlis$bed_perc9 <- (perlis$active_cases9/(perlis$hbed*0.2))*100
kedah$bed_perc9 <- (kedah$active_cases9/(kedah$hbed*0.2))*100
penang$bed_perc9 <- (penang$active_cases9/(penang$hbed*0.2))*100
perak$bed_perc9 <- (perak$active_cases9/(perak$hbed*0.2))*100
selangor$bed_perc9 <- (selangor$active_cases9/(selangor$hbed*0.2))*100
kl$bed_perc9 <- (kl$active_cases9/(kl$hbed*0.2))*100
putrajaya$bed_perc9 <- (putrajaya$active_cases9/(putrajaya$hbed*0.2))*100
melaka$bed_perc9 <- (melaka$active_cases9/(melaka$hbed*0.2))*100
negeri$bed_perc9 <- (negeri$active_cases9/(negeri$hbed*0.2))*100
johor$bed_perc9 <- (johor$active_cases9/(johor$hbed*0.2))*100
pahang$bed_perc9 <- (pahang$active_cases9/(pahang$hbed*0.2))*100
kelantan$bed_perc9 <- (kelantan$active_cases9/(kelantan$hbed*0.2))*100
terengganu$bed_perc9 <- (terengganu$active_cases9/(terengganu$hbed*0.2))*100
sabah$bed_perc9 <- (sabah$active_cases9/sabah$hbed)*100
sarawak$bed_perc9 <- (sarawak$active_cases9/(sarawak$hbed*0.2))*100
labuan$bed_perc9 <- (labuan$active_cases9/labuan$hbed)*100
#add ventilator lines
#sabah_ven <- state_data_v2$ventilator[state_data_v2$state=="Sabah_latest"]

#combine all the states into a single dataset
#row join all the data frames
state_full <- rbind(perlis, kedah, penang, perak,selangor,
                       kl, putrajaya, negeri, melaka, johor,
                       pahang, terengganu, kelantan, sabah, 
                       sarawak, labuan)


mas_state <- full_join(ts_mas, state_full, by=c("state","date","incidence","incidence14_rate","bed_perc5"))

mas_state <- mas_state%>% filter(date>as.Date("2020-03-19"))

```


```{r, include=FALSE}
#data set for incidence curves
#change selected state spelling
state$region[state$state=="Perlis"] <- 'Northern region'
state$region[state$state=="Kedah"] <- 'Northern region'
state$region[state$state=="Pulau Pinang"] <- 'Northern region'
state$region[state$state=="Perak"] <- 'Northern region'
state$region[state$state=="Selangor"] <- 'Central region'
state$region[state$state=="Negeri Sembilan"] <- 'Southern region'
state$region[state$state=="Melaka"] <- 'Southern region'
state$region[state$state=="Johor"] <- 'Southern region'
state$region[state$state=="Pahang"] <- 'Eastern region'
state$region[state$state=="Terengganu"] <- "Eastern region"
state$region[state$state=="Kelantan"] <- 'Eastern region'
state$region[state$state=="Sabah"] <- 'Sabah & W.P. Labuan'
state$region[state$state=="Sarawak"] <- 'Sarawak only'
state$region[state$state=="W.P. Labuan"] <- 'Sabah & W.P. Labuan'
state$region[state$state=="W.P. Kuala Lumpur"] <- "Central region"
state$region[state$state=="W.P. Putrajaya"] <- 'Central region'

#group by regions and sum up new region cases
region <- state %>% select(date,region,new_cases,total_cases) %>% group_by(date,region) %>% summarise(new=sum(new_cases), total=sum(total_cases))
colnames(region) <- c("date","location","new_cases", "total_cases")

#add populations for all states
#state populations
#state populations
johor1 <- 3764300
kedah1	<- 2180600
kelantan1 <- 1885700
melaka1 <- 930700
negeri1 <- 	1245700
pahang1 <-1674600
perak1 <- 2512100
perlis1 <- 254000
penang1 <- 1774600
sabah1	<- 3903400
sarawak1	<- 2812800
selangor1	<- 6528400
terengganu1	<- 1245700
kl1	<- 1780700
labuan1	<- 99300
putrajaya1	<- 103800
central <- selangor1+putrajaya1+kl1
northern <- kedah1+perak1+perlis1+penang1
eastern <- kelantan1+terengganu1+pahang1
southern <- johor1+melaka1+negeri1
sarawak1 <- sarawak1
sabah2 <- sabah1+labuan1

#add a total population column
region$population <- NA
region$population[region$location=="Central region"] <- central
region$population[region$location=="Sarawak only"] <- sarawak1
region$population[region$location=="Sabah & W.P. Labuan"] <- sabah2
region$population[region$location=="Eastern region"] <- eastern
region$population[region$location=="Northern region"] <- northern
region$population[region$location=="Southern region"] <- southern
state$population <- NA
state$population[state$state=="Perlis"] <- perlis1
state$population[state$state=="Kedah"] <- kedah1
state$population[state$state=="Pulau Pinang"] <- penang1
state$population[state$state=="Perak"] <- perak1
state$population[state$state=="Selangor"] <- selangor1
state$population[state$state=="Negeri Sembilan"] <- negeri1
state$population[state$state=="Melaka"] <- melaka1
state$population[state$state=="Johor"] <- johor1
state$population[state$state=="Pahang"] <- pahang1
state$population[state$state=="Terengganu"] <- terengganu1
state$population[state$state=="Kelantan"] <- kelantan1
state$population[state$state=="Sabah"] <- sabah1
state$population[state$state=="Sarawak"] <- sarawak1
state$population[state$state=="W.P. Labuan"] <- labuan1
state$population[state$state=="W.P. Kuala Lumpur"] <- kl1
state$population[state$state=="W.P. Putrajaya"] <- putrajaya1

#calculate the 14-day sum of cases in all countries
region<- region %>% group_by(location) %>% 
  mutate(incident14=roll_sum(new_cases, 14,fill=NA, align="right"))

state <- state %>% group_by(state) %>% 
  mutate(incident14=roll_sum(new_cases, 14,fill=NA, align="right"))

#calculate the 14 day incidence density per 100k for all states
region <- region %>% group_by(date,location) %>% mutate(incident14_rate=round((incident14/population)*100000,2))
region <- region %>% group_by(date,location) %>% mutate(incidence=round((total_cases/population)*100000,2))
state <- state %>% group_by(date,state) %>% mutate(incident14_rate=round((incident14/population)*100000,2))
state <- state %>% group_by(date,state) %>% mutate(incidence=round((total_cases/population)*100000,2))

#select and combine
#join state and region
state_incidence <- as.data.frame(cbind(as.character(state$state), as.numeric(state$incidence), as.numeric(state$incident14_rate)))
state_incidence$date <- as.Date(state$date)
colnames(state_incidence) <- c("state","incidence","incidence14", "date")
state_incidence$incidence2 <- NA
state_incidence$incidence14_2 <- NA
state_incidence$location <-  NA
region_incidence <- as.data.frame(cbind(as.character(region$location), as.numeric(region$incidence), as.numeric(region$incident14_rate)))
region_incidence$date <- as.Date(region$date)
colnames(region_incidence) <- c("location","incidence2","incidence14_2","date")
region_incidence$incidence <- NA
region_incidence$incidence14 <- NA
region_incidence$state <-  NA

#combine state and region
incidence_df <- rbind(region_incidence, state_incidence)

#for some reason (likely the NAs) all numeric columns turn into characters
incidence_df$incidence <- as.numeric(incidence_df$incidence)
incidence_df$incidence2 <- as.numeric(incidence_df$incidence2)
incidence_df$incidence14 <- as.numeric(incidence_df$incidence14)
incidence_df$incidence14_2 <- as.numeric(incidence_df$incidence14_2)

#division variable
incidence_df <- incidence_df%>% mutate(group=ifelse(location %in% NA, "state", "region"))
```

